Debug

diff --git a/validation/pipeline/airgap/Jenkinsfile.airgap.tests b/validation/pipeline/airgap/Jenkinsfile.airgap.tests
--- a/validation/pipeline/airgap/Jenkinsfile.airgap.tests
+++ b/validation/pipeline/airgap/Jenkinsfile.airgap.tests
@@ -2,25 +2,27 @@
 node {
   def homePath = pwd() + "/"
   def rootPath = "/root/go/src/github.com/rancher/tfp-automation/"
+  def testRootPath = "/root/go/src/github.com/rancher/tests/"
   def TERRAFORM_DIR = './root/go/src/github.com/rancher/tfp-automation/modules/airgap'
+  def configYmlPath = "./root/go/src/github.com/rancher/tfp-automation"
   def testsDir = "github.com/rancher/tfp-automation/tests/${env.TEST_PACKAGE}"
   def filename = "config.yml"
-  def configPath = ""
   def job_name = "${JOB_NAME}"
   if (job_name.contains('/')) { 
     job_names = job_name.split('/')
     job_name = job_names[job_names.size() - 1] 
   }
+  def configGeneratorContainer = "${job_name}${env.BUILD_NUMBER}_generator"
+  def golangTestContainer = "${job_name}${env.BUILD_NUMBER}_golangtest"
   def testContainer = "${job_name}${env.BUILD_NUMBER}_test"
   def imageName = "tfp-automation-validation-${job_name}${env.BUILD_NUMBER}"
   def testResultsOut = "results.xml"
   def testResultsJSON = "results.json"
   def envFile = ".env"
   def config = env.CONFIG
-  def runFlag = "AirGap"
-  def rancherUrl = ""
-  def rancherPassword = ""
+  def adminToken = ""
   def privateRegistry = ""
+  def validationVolume = "ValidationSharedVolume-${job_name}${env.BUILD_NUMBER}"
 
   def infraBranch = "${env.INFRA_BRANCH}"
   if ("${env.INFRA_BRANCH}" != "null" && "${env.INFRA_BRANCH}" != "") {
@@ -45,90 +47,145 @@ node {
   def testPackage = "airgap/"
   //def testCaseName = `-run \"TestWorkloadUpgradeTestSuite/TestWorkloadPreUpgrade\"`
 
-  withCredentials([ string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
-                    string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY'),
-                    string(credentialsId: 'AWS_SSH_PEM_KEY', variable: 'AWS_SSH_PEM_KEY'),
-                    string(credentialsId: 'AWS_SSH_KEY_NAME', variable: 'AWS_SSH_KEY_NAME')]){
+    wrap([$class: 'AnsiColorBuildWrapper', 'colorMapName': 'XTerm', 'defaultFg': 2, 'defaultBg':1]) {
+        withFolderProperties {
+            paramsMap = []
+            params.each {
+                if (it.value && it.value.trim() != "") {
+                    paramsMap << "$it.key=$it.value"
+                }
+            }
+            withCredentials([ string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
+                              string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY'),
+                              string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'RANCHER_EKS_ACCESS_KEY'),
+                              string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'RANCHER_EKS_SECRET_KEY'),
+                              string(credentialsId: 'AWS_SSH_PEM_KEY', variable: 'AWS_SSH_PEM_KEY'),
+                              string(credentialsId: 'RANCHER_SSH_KEY', variable: 'RANCHER_SSH_KEY'),
+                              string(credentialsId: 'AWS_SSH_RSA_KEY', variable: 'AWS_SSH_RSA_KEY'),
+                              string(credentialsId: 'AWS_SSH_KEY_NAME', variable: 'AWS_SSH_KEY_NAME'),
+                              string(credentialsId: 'RANCHER_REGISTRY_USER_NAME', variable: 'RANCHER_REGISTRY_USER_NAME'),
+                              string(credentialsId: 'RANCHER_REGISTRY_PASSWORD', variable: 'RANCHER_REGISTRY_PASSWORD'),
+                              string(credentialsId: 'ADMIN_PASSWORD', variable: 'ADMIN_PASSWORD'),
+                              string(credentialsId: 'USER_PASSWORD', variable: 'USER_PASSWORD'),
+                              string(credentialsId: 'RANCHER_VALID_TLS_CERT', variable: 'RANCHER_VALID_TLS_CERT'),
+                              string(credentialsId: 'RANCHER_VALID_TLS_KEY', variable: 'RANCHER_VALID_TLS_KEY')]) {
+          
+                withEnv(paramsMap) {
 
-    stage('Checkout Infrastructure Repo') {
-        deleteDir()
-        checkout([
-                    $class: 'GitSCM',
-                    branches: [[name: "*/${infraBranch}"]],
-                    extensions: scm.extensions + [[$class: 'CleanCheckout']],
-                    userRemoteConfigs: infraRepo
-                ])
-     }
 
-    stage('Configure and Build') {
-        config = config.replace('${AWS_SECRET_ACCESS_KEY}', env.AWS_SECRET_ACCESS_KEY)
-        config = config.replace('${AWS_ACCESS_KEY_ID}', env.AWS_ACCESS_KEY_ID)
+                    stage('Checkout Infrastructure Repo') {
+                        deleteDir()
+                        checkout([
+                                    $class: 'GitSCM',
+                                    branches: [[name: "*/${infraBranch}"]],
+                                    extensions: scm.extensions + [[$class: 'CleanCheckout']],
+                                    userRemoteConfigs: infraRepo
+                                ])
+                     }
 
-        writeFile file: filename, text: config
+                    stage('Configure and Build') {
+                        config = config.replace('${AWS_SECRET_ACCESS_KEY}', env.AWS_SECRET_ACCESS_KEY)
+                        config = config.replace('${AWS_ACCESS_KEY_ID}', env.AWS_ACCESS_KEY_ID)
+                
+                        writeFile file: filename, text: config
+                
+                        dir(".ssh") {
+                            def decoded = new String(env.AWS_SSH_PEM_KEY.decodeBase64())
+                            writeFile file: AWS_SSH_KEY_NAME, text: decoded
+                    
+                            def decodedRsa = new String(AWS_SSH_RSA_KEY.decodeBase64())
+                            writeFile file: JENKINS_RKE_VALIDATION, text: decodedRsa
+                        }
+                        
+                        env.CATTLE_TEST_CONFIG=rootPath+filename
+                
+                        sh "./configure.sh"
+                        sh "./build.sh"
+                     }
 
-        def decoded = new String(env.AWS_SSH_PEM_KEY.decodeBase64())
-        writeFile file: 'key.pem', text: decoded
-        
-        env.CATTLE_TEST_CONFIG=rootPath+filename
-        configPath = "./rancher/tests/v2/validation/${filename}"
+                    stage('Run Infrastructure Module Test') {
+                        try {
+                            sh """
+                            docker run --name ${testContainer} -t --env-file ${envFile} ${imageName} sh -c "
+                            /root/go/bin/gotestsum --format standard-verbose --packages=${testsDir} --junitfile ${testResultsOut} --jsonfile ${testResultsJSON} -- -timeout=${timeout} -v ${params.TEST_CASE} | tee /root/test_logs.txt"
+                            """
+                            sh "docker cp ${testContainer}:/root/ ./"
+              
+                            adminToken = sh(script: "grep 'Admin bearer token:' ./root/test_logs.txt  || true ", returnStdout: true).trim()
+                            echo "Admin token: ${adminToken}"
+                            privateRegistry = sh(script: "grep 'Private registry:' ./root/test_logs.txt  || true  ", returnStdout: true).trim()
+                            echo "Private registry:  ${privateRegistry}"
 
-        sh "./configure.sh"
-        sh "./build.sh"
-     }
 
-    stage('Run Infrastructure Module Test') {
-        try {
-            sh """
-            docker run --name ${testContainer} -t -v ${homePath}key.pem:${rootPath}key.pem --env-file ${envFile} -v ${homePath}/tfp_output.log:/root/tfp_output.log ${imageName} sh -c "
-            /root/go/bin/gotestsum --format standard-verbose --packages=${testsDir} --junitfile ${testResultsOut} --jsonfile ${testResultsJSON} -- -timeout=${timeout} -v ${params.TEST_CASE};
-            if [ -f ${rootPath}reporter ]; then ${rootPath}reporter; fi"
-            """
-            sh "docker cp ${testContainer}:/root/ ./"
+                        } catch(err) {
+                            echo 'Test run had failures. Collecting results...'
+                        }
+                     }
 
-            // rancherPassword = sh(script: "yq '.rancher_url' tfpOutput", returnStdout: true).trim()
-            // rancherUrl = sh(script: "awk -F'URL: ' '/Rancher server URL:/ {print \$2}' tfp_output.log", returnStdout: true).trim()
-            // rancherPassword = sh(script: "awk -F'password: ' '/Booststrap password:/ {print \$2}' tfp_output.log", returnStdout: true).trim()
-            // privateRegistry = sh(script: "awk -F'registry: ' '/Private registry:/ {print \$2}' tfp_output.log", returnStdout: true).trim()
+                    stage('Checkout Test Repo') {
+                        checkout([  
+                                    $class: 'GitSCM',
+                                    branches: [[name: "*/${testBranch}"]],
+                                    extensions: scm.extensions + [[$class: 'CleanCheckout']],
+                                    userRemoteConfigs: testRepo
+                                ])
+                    }
 
-        } catch(err) {
-            echo 'Test run had failures. Collecting results...'
-        }
-     }
+                    dir ("./") {
+                        stage('Configure and Build') {
+                          if (env.AWS_SSH_PEM_KEY && env.AWS_SSH_KEY_NAME) {
+                            dir("./validation/.ssh") {
+                              def decoded = new String(AWS_SSH_PEM_KEY.decodeBase64())
+                              writeFile file: AWS_SSH_KEY_NAME, text: decoded
+                            }
+                          }
+                          dir("./validation") {
+                            filename = "config.yaml"
+                            def configContents = env.CONFIG
+                            
+                            config = config.replace('${PRIVATE_REGISTRY}', privateRegistry)
+                            config = config.replace('${ADMIN_TOKEN}', adminToken)
+                            echo "$config"
+            
+                            writeFile file: filename, text: configContents
+                            env.CATTLE_TEST_CONFIG = testRootPath+filename
+                          }
+                          dir ("./") {
+                            sh "./validation/configure.sh"
+                            sh "docker build . -f ./validation/Dockerfile.validation --build-arg CORRAL_VERSION=${env.CORRAL_VERSION} -t ${imageName}"
+                            sh "docker volume create --name ${validationVolume}"
+                          }
+                        }
+                        stage('Run Validation Tests') {
+                          try {
+                            sh "docker run --rm -v ${validationVolume}:/root ${imageName} sh -c 'ls -lR /root' "
 
-    stage('Checkout Test Repo') {
-        checkout([  
-                    $class: 'GitSCM',
-                    branches: [[name: "*/${testBranch}"]],
-                    extensions: scm.extensions + [[$class: 'CleanCheckout']],
-                    userRemoteConfigs: testRepo
-                ])
-    }
 
-    stage('Setup') {
-        sh returnStdout: true, script: 'wget -qO ./yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64'
-        sh returnStdout:true, script: 'chmod a+x ./yq'
-     }
-
-    stage('Run Downstream cluster tests'){
-        sh "./configure.sh"
-        sh "./build.sh"
-        
-        def configYaml = readFile(file: "${configPath}")
-        def goValidationParams = [
-            text(name: 'CONFIG', value: configYaml),
-            string(name: 'BRANCH', value: "main"),
-            string(name: 'TEST_RUN_NAME', value: ${testPackage}),
-            string(name: 'GOTEST_TESTCASE', value: "${[runFlag]} -p 1"),
-        ]
-
-        jobs["$testTag-test-validation"] = { build job: 'go-automation-freeform-job', parameters: goValidationParams }
-    
-    }
-
-    stage('Cleanup terraform resources'){
-        sh """
-            docker exec $testContainer sh -c "chmod +x -R /terraform-files && terraform -chdir=/terraform-files init && terraform -chdir=/terraform-files destroy -auto-approve"
-        """
-     } //cleanup
-  } //credentials
+                            sh "docker run -v ${validationVolume}:/root --name ${golangTestContainer} -t --env-file ${envFile} " +
+                            "${imageName} sh -c \"gotestsum --format standard-verbose --packages=/root/go/src/github.com/rancher/tests/validation/airgap -- -tags=\"airgap\" --junitfile ${testResultsOut}  --jsonfile ${testResultsJSON}  -timeout=${timeout} \""
+                          } catch(err) {
+                            echo 'Validation tests had failures. Aborting'
+                          }
+                          sh """
+                          docker rm ${golangTestContainer}
+                          docker volume rm ${validationVolume}
+                          docker rmi ${imageName}
+                          
+                          """
+                        }
+            
+                        stage('Cleanup terraform resources'){
+                            sh """
+                                docker run --rm \
+                                -v $TERRAFORM_DIR:/terraform-files \
+                                -w /terraform-files \
+                                hashicorp/terraform:latest \
+                                /bin/sh -c 'chmod -R +x /terraform-files && terraform init && terraform destroy -auto-approve'
+                            """
+                         } //cleanup
+                    }//dir
+                } //params
+            } //credentials
+        } //folder properties
+    } //wrap
 } // node
